version: "3.9"

services:
  pharos-mongo:
    image: mongo:7
    container_name: pharos-mongo
    restart: unless-stopped
    ports:
      - "6444:27017"
    environment:
      MONGO_INITDB_DATABASE: pharos
      MONGO_INITDB_ROOT_USERNAME: pharos
      MONGO_INITDB_ROOT_PASSWORD: pharos_password
    volumes:
      - pharos_data:/data/db

volumes:
  pharos_data:
